apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-cartservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop-cartservice
  template:
    metadata:
      labels:
        app: eshop-cartservice
    spec:
      containers:
        - name: eshop-cartservice
          image: gcr.io/architect-certification-289902/22/eshop-cartservice@sha256:872a0e6e2f44db3738f8a06775f04da1033ea516d62d154bc9ba3635db7e0a6b
          ports:
          - containerPort: 8091
          env:
            - name: SPRING_REDIS_CLUSTER_NODES
              value: redis-redis-cluster.default.svc.cluster.local:6379
            - name: SPRING_REDIS_CLUSTER_MAX-REDIRECTS
              value: "3"
            - name: NATS_SPRING_SERVER
              value: "nats://nats-cluster:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-cartservice
spec:
  type: ClusterIP
  selector:
    app: eshop-cartservice
  ports:
  - port: 8091