apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-frontend-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-frontend
  template:
    metadata:
      labels:
        app: eshop-frontend
        version: v1
    spec:
      containers:
        - name: eshop-frontend
          image: gcr.io/architect-certification-289902/22/eshop-frontend@sha256:2fa5a0ac81751e673226759e7789bc6a80333a0313f531cafd5d4159a4ff6e24
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-frontend-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-frontend
  template:
    metadata:
      labels:
        app: eshop-frontend
        version: v2
    spec:
      containers:
        - name: eshop-frontend
          image: gcr.io/architect-certification-289902/22/eshop-frontend@sha256:7c633f23c17ac8b0671e4a7ae557700e61f34d11b3ac69a5903c60e1b2aafd29
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-frontend
spec:
  type: ClusterIP
  selector:
    app: eshop-frontend
  ports:
  - port: 8080